### ISSUE TITLE
请问可以提供数据库数据吗？

### ISSUE THREAD

**Issue by markoxu** [wangyushun/MovieDiary#1]
您好，我是一名学生，正在B站学习Django框架，看到您的博客做的非常不错，想作为一个模版进行学习，但是仓库里面好像没有数据库数据，不知道是否可以提供数据库数据（删减版也可以）呢？感谢感谢。

**Comment by wangyushun** [comment]
http://obs.cstcloud.cn/share/obs/www/moviediary.backup.zip

**Comment by wangyushun** [comment]
@MarkoXyz http://obs.cstcloud.cn/share/obs/www/moviediary.backup.zip

**Comment by markoxu** [comment]
感谢感谢！我认真学习一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shun"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 中午11:05
收件人:&nbsp;"wangyushun/MovieDiary"<MovieDiary@noreply.github.com&gt;;
抄送:&nbsp;"徐奕湛"<704712641@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wangyushun/MovieDiary] 请问可以提供数据库数据吗？ (#1)




@MarkoXyz http://obs.cstcloud.cn/share/obs/www/moviediary.backup.zip
